name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
        install-java: false
        install-pods: false

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install NPM Modules
      run: |
        npm i -g pnpm
        CI=false pnpm i
    - name: Build
      run: |
        CI=false ionic build --prod -- --base-href 'https://rasyid.dev/educator-app/'
        ls build

    - name: Deploy
      uses: ftnext/action-push-ghpages@v1.0.0
      with:
        build_dir: build
        github_token: ${{ secrets.GITHUB_TOKEN  }} 
